#![allow(missing_docs)]

use heck::ToUpperCamelCase;
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
};

const CORE_ICONS: &[&str] = &[
    "add",
    "arrow-down",
    "arrow-up",
    "calendar",
    "check",
    "check-circle",
    "check-circle-filled",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "close",
    "close-circle",
    "ellipsis",
    "error-circle",
    "file",
    "image",
    "info-circle",
    "loading",
    "minus",
    "more",
    "search",
    "star",
    "star-filled",
    "time",
    "upload",
];

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let icon_dir = manifest_dir.join("assets/icons");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));
    println!("cargo:rerun-if-changed={}", icon_dir.display());

    assert!(
        icon_dir.is_dir(),
        "missing icon directory {}",
        icon_dir.display()
    );
    let mut icons = BTreeMap::<String, String>::new();
    for entry in fs::read_dir(&icon_dir).expect("read icon directory") {
        let entry = entry.expect("read icon entry");
        let path = entry.path();
        if path.extension().and_then(|value| value.to_str()) != Some("svg") {
            continue;
        }
        validate_svg(&path);
        let name = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("UTF-8 icon name")
            .to_owned();
        let variant = variant_name(&name);
        if let Some(previous) = icons.insert(name.clone(), variant.clone()) {
            panic!("duplicate icon {name}: {previous} and {variant}");
        }
    }
    assert!(
        !icons.is_empty(),
        "no SVG icons found in {}",
        icon_dir.display()
    );
    for core in CORE_ICONS {
        assert!(
            icons.contains_key(*core),
            "required core icon {core:?} is missing"
        );
    }

    let mut variants = BTreeSet::new();
    for (name, variant) in &icons {
        if !variants.insert(variant.clone()) {
            panic!("icon variant collision for {name}: {variant}");
        }
    }

    let full_icons = env::var_os("CARGO_FEATURE_FULL_ICONS").is_some();
    let available = icons
        .iter()
        .filter(|(name, _)| full_icons || CORE_ICONS.contains(&name.as_str()))
        .map(|(name, variant)| (name.clone(), variant.clone()))
        .collect::<Vec<_>>();

    write_icon_names(&out_dir.join("icon_names.rs"), &icons);
    write_embedded_assets(&out_dir.join("embedded_assets.rs"), &available);
}

fn validate_svg(path: &Path) {
    let source = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("failed reading {}: {error}", path.display());
    });
    let lowered = source.to_ascii_lowercase();
    for forbidden in [
        "<script",
        "javascript:",
        "<foreignobject",
        "xlink:href=\"http",
        "href=\"http",
        "xlink:href='http",
        "href='http",
    ] {
        assert!(
            !lowered.contains(forbidden),
            "unsafe SVG construct {forbidden:?} in {}",
            path.display()
        );
    }
    assert!(lowered.contains("<svg"), "not an SVG: {}", path.display());
}

fn variant_name(name: &str) -> String {
    let mut variant = name.to_upper_camel_case();
    if variant.is_empty() {
        variant.push_str("Unknown");
    }
    if variant.chars().next().is_some_and(char::is_numeric) {
        variant.insert_str(0, "Icon");
    }
    variant
}

fn write_icon_names(path: &Path, icons: &BTreeMap<String, String>) {
    let mut source = String::from(
        "// @generated by build.rs; do not edit.\n\
         #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
         #[cfg_attr(feature = \"serde\", derive(serde::Deserialize, serde::Serialize))]\n\
         pub enum IconName {\n",
    );
    for variant in icons.values() {
        source.push_str("    ");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str("}\n\n#[allow(missing_docs)]\nimpl IconName {\n");
    source.push_str("    pub const ALL: &'static [Self] = &[\n");
    for variant in icons.values() {
        source.push_str("        Self::");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str(
        "    ];\n\n    pub const fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for (name, variant) in icons {
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => \"");
        source.push_str(name);
        source.push_str("\",\n");
    }
    source.push_str(
        "        }\n    }\n\n\
         pub fn asset_path(self) -> gpui::SharedString {\n\
             format!(\"tdesign/icons/{}.svg\", self.as_str()).into()\n\
         }\n}\n\n\
         impl std::fmt::Display for IconName {\n\
             fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n\
                 formatter.write_str(self.as_str())\n\
             }\n\
         }\n\n\
         impl std::str::FromStr for IconName {\n\
             type Err = UnknownIcon;\n\
             fn from_str(value: &str) -> Result<Self, Self::Err> {\n\
                 match value {\n",
    );
    for (name, variant) in icons {
        source.push_str("            \"");
        source.push_str(name);
        source.push_str("\" => Ok(Self::");
        source.push_str(variant);
        source.push_str("),\n");
    }
    source.push_str(
        "                    other => Err(UnknownIcon(other.to_owned())),\n\
                 }\n\
             }\n\
         }\n",
    );
    fs::write(path, source).expect("write generated icon names");
}

fn write_embedded_assets(path: &Path, icons: &[(String, String)]) {
    let mut source = String::from(
        "// @generated by build.rs; do not edit.\n\
         pub(crate) static EMBEDDED_PATHS: &[&str] = &[\n",
    );
    for (name, _) in icons {
        source.push_str("    \"tdesign/icons/");
        source.push_str(name);
        source.push_str(".svg\",\n");
    }
    source.push_str(
        "];\n\n\
         pub(crate) fn embedded(path: &str) -> Option<&'static [u8]> {\n\
             match path {\n",
    );
    for (name, _) in icons {
        source.push_str("        \"tdesign/icons/");
        source.push_str(name);
        source.push_str(
            ".svg\" => Some(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/",
        );
        source.push_str(name);
        source.push_str(".svg\"))),\n");
    }
    source.push_str("        _ => None,\n    }\n}\n");
    fs::write(path, source).expect("write generated embedded assets");
}
