// @generated by cargo xtask upstream sync; do not edit.
#[allow(missing_docs)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UpstreamThemeToken {
    pub name: &'static str,
    pub value: &'static str,
    pub mode: &'static str,
}

#[allow(missing_docs)]
pub static TDESIGN_WEB_TOKENS: &[UpstreamThemeToken] = &[
    UpstreamThemeToken {
        name: "@anim-duration-base",
        value: "0.2s",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@anim-duration-moderate",
        value: "0.24s",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@anim-duration-slow",
        value: "0.28s",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@anim-time-fn-ease-in",
        value: "cubic-bezier(0.82, 0, 1, 0.9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@anim-time-fn-ease-out",
        value: "cubic-bezier(0, 0, 0.15, 1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@anim-time-fn-easing",
        value: "cubic-bezier(0.38, 0, 0.24, 1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-component",
        value: "var(--td-bg-color-component)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-component-active",
        value: "var(--td-bg-color-component-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-component-disabled",
        value: "var(--td-bg-color-component-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-component-hover",
        value: "var(--td-bg-color-component-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-container",
        value: "var(--td-bg-color-container)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-container-active",
        value: "var(--td-bg-color-container-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-container-hover",
        value: "var(--td-bg-color-container-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-container-select",
        value: "var(--td-bg-color-container-select)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-page",
        value: "var(--td-bg-color-page)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycomponent",
        value: "var(--td-bg-color-secondarycomponent)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycomponent-active",
        value: "var(--td-bg-color-secondarycomponent-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycomponent-hover",
        value: "var(--td-bg-color-secondarycomponent-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycontainer",
        value: "var(--td-bg-color-secondarycontainer)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycontainer-active",
        value: "var(--td-bg-color-secondarycontainer-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-secondarycontainer-hover",
        value: "var(--td-bg-color-secondarycontainer-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@bg-color-specialcomponent",
        value: "var(--td-bg-color-specialcomponent)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-level-1-color",
        value: "var(--td-border-level-1-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-level-2-color",
        value: "var(--td-border-level-2-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-circle",
        value: "var(--td-radius-circle)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-default",
        value: "var(--td-radius-default)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-extraLarge",
        value: "var(--td-radius-extraLarge)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-large",
        value: "var(--td-radius-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-medium",
        value: "var(--td-radius-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-round",
        value: "var(--td-radius-round)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@border-radius-small",
        value: "var(--td-radius-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color",
        value: "var(--td-brand-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-1",
        value: "var(--td-brand-color-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-10",
        value: "var(--td-brand-color-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-2",
        value: "var(--td-brand-color-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-3",
        value: "var(--td-brand-color-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-4",
        value: "var(--td-brand-color-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-5",
        value: "var(--td-brand-color-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-6",
        value: "var(--td-brand-color-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-7",
        value: "var(--td-brand-color-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-8",
        value: "var(--td-brand-color-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-9",
        value: "var(--td-brand-color-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-active",
        value: "var(--td-brand-color-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-disabled",
        value: "var(--td-brand-color-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-focus",
        value: "var(--td-brand-color-focus)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-hover",
        value: "var(--td-brand-color-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-light",
        value: "var(--td-brand-color-light)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@brand-color-light-hover",
        value: "var(--td-brand-color-light-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-l",
        value: "var(--td-comp-margin-l)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-m",
        value: "var(--td-comp-margin-m)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-s",
        value: "var(--td-comp-margin-s)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xl",
        value: "var(--td-comp-margin-xl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xs",
        value: "var(--td-comp-margin-xs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xxl",
        value: "var(--td-comp-margin-xxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xxs",
        value: "var(--td-comp-margin-xxs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xxxl",
        value: "var(--td-comp-margin-xxxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-margin-xxxxl",
        value: "var(--td-comp-margin-xxxxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-l",
        value: "var(--td-comp-paddingLR-l)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-m",
        value: "var(--td-comp-paddingLR-m)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-s",
        value: "var(--td-comp-paddingLR-s)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-xl",
        value: "var(--td-comp-paddingLR-xl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-xs",
        value: "var(--td-comp-paddingLR-xs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-xxl",
        value: "var(--td-comp-paddingLR-xxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingLR-xxs",
        value: "var(--td-comp-paddingLR-xxs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-l",
        value: "var(--td-comp-paddingTB-l)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-m",
        value: "var(--td-comp-paddingTB-m)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-s",
        value: "var(--td-comp-paddingTB-s)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-xl",
        value: "var(--td-comp-paddingTB-xl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-xs",
        value: "var(--td-comp-paddingTB-xs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-xxl",
        value: "var(--td-comp-paddingTB-xxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-paddingTB-xxs",
        value: "var(--td-comp-paddingTB-xxs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-l",
        value: "var(--td-comp-size-l)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-m",
        value: "var(--td-comp-size-m)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-s",
        value: "var(--td-comp-size-s)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xl",
        value: "var(--td-comp-size-xl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xs",
        value: "var(--td-comp-size-xs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxl",
        value: "var(--td-comp-size-xxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxs",
        value: "var(--td-comp-size-xxs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxxl",
        value: "var(--td-comp-size-xxxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxxs",
        value: "var(--td-comp-size-xxxs)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxxxl",
        value: "var(--td-comp-size-xxxxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@comp-size-xxxxxl",
        value: "var(--td-comp-size-xxxxxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@component-border",
        value: "var(--td-component-border)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@component-stroke",
        value: "var(--td-component-stroke)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color",
        value: "var(--td-error-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-1",
        value: "var(--td-error-color-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-10",
        value: "var(--td-error-color-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-2",
        value: "var(--td-error-color-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-3",
        value: "var(--td-error-color-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-4",
        value: "var(--td-error-color-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-5",
        value: "var(--td-error-color-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-6",
        value: "var(--td-error-color-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-7",
        value: "var(--td-error-color-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-8",
        value: "var(--td-error-color-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-9",
        value: "var(--td-error-color-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-active",
        value: "var(--td-error-color-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-disabled",
        value: "var(--td-error-color-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-focus",
        value: "var(--td-error-color-focus)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-hover",
        value: "var(--td-error-color-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-light",
        value: "var(--td-error-color-light)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@error-color-light-hover",
        value: "var(--td-error-color-light-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-body-large",
        value: "var(--td-font-body-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-body-medium",
        value: "var(--td-font-body-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-body-small",
        value: "var(--td-font-body-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-display-large",
        value: "var(--td-font-display-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-display-medium",
        value: "var(--td-font-display-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-family",
        value: "var(--td-font-family)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-family-medium",
        value: "var(--td-font-family-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-gray-1",
        value: "var(--td-font-gray-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-gray-2",
        value: "var(--td-font-gray-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-gray-3",
        value: "var(--td-font-gray-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-gray-4",
        value: "var(--td-font-gray-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-headline-large",
        value: "var(--td-font-headline-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-headline-medium",
        value: "var(--td-font-headline-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-headline-small",
        value: "var(--td-font-headline-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-link-large",
        value: "var(--td-font-link-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-link-medium",
        value: "var(--td-font-link-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-link-small",
        value: "var(--td-font-link-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-mark-medium",
        value: "var(--td-font-mark-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-mark-small",
        value: "var(--td-font-mark-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size",
        value: "10px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size-base",
        value: "var(--td-font-size-body-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size-l",
        value: "var(--td-font-size-body-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size-s",
        value: "var(--td-font-size-body-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size-xl",
        value: "var(--td-font-size-title-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-size-xxl",
        value: "var(--td-font-size-headline-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-title-extraLarge",
        value: "var(--td-font-title-extraLarge)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-title-large",
        value: "var(--td-font-title-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-title-medium",
        value: "var(--td-font-title-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-title-small",
        value: "var(--td-font-title-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-white-1",
        value: "var(--td-font-white-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-white-2",
        value: "var(--td-font-white-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-white-3",
        value: "var(--td-font-white-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@font-white-4",
        value: "var(--td-font-white-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@form-bg-color",
        value: "@bg-color-container",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@form-border-color",
        value: "@border-level-2-color",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@form-height",
        value: "30px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@form-text-color",
        value: "@text-color-primary",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-1",
        value: "var(--td-gray-color-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-10",
        value: "var(--td-gray-color-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-11",
        value: "var(--td-gray-color-11)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-12",
        value: "var(--td-gray-color-12)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-13",
        value: "var(--td-gray-color-13)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-14",
        value: "var(--td-gray-color-14)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-2",
        value: "var(--td-gray-color-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-3",
        value: "var(--td-gray-color-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-4",
        value: "var(--td-gray-color-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-5",
        value: "var(--td-gray-color-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-6",
        value: "var(--td-gray-color-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-7",
        value: "var(--td-gray-color-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-8",
        value: "var(--td-gray-color-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@gray-color-9",
        value: "var(--td-gray-color-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@icon-default",
        value: "16px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@icon-l",
        value: "24px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@mask-active",
        value: "var(--td-mask-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@mask-bg",
        value: "var(--td-mask-background)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@mask-disabled",
        value: "var(--td-mask-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@pop-padding-l",
        value: "var(--td-pop-padding-l)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@pop-padding-m",
        value: "var(--td-pop-padding-m)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@pop-padding-s",
        value: "var(--td-pop-padding-s)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@pop-padding-xl",
        value: "var(--td-pop-padding-xl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@pop-padding-xxl",
        value: "var(--td-pop-padding-xxl)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@prefix",
        value: "t",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-lg",
        value: "1200px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-lg-min",
        value: "@screen-lg",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-md",
        value: "992px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-md-min",
        value: "@screen-md",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-sm",
        value: "768px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-sm-min",
        value: "@screen-sm",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xl",
        value: "1400px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xl-min",
        value: "@screen-xl",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xs",
        value: "320px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xs-min",
        value: "@screen-xs",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xxl",
        value: "1880px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@screen-xxl-min",
        value: "@screen-xxl",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@scroll-track-color",
        value: "var(--td-scroll-track-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@scrollbar-color",
        value: "var(--td-scrollbar-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@scrollbar-hover-color",
        value: "var(--td-scrollbar-hover-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-1",
        value: "var(--td-shadow-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-2",
        value: "var(--td-shadow-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-2-inset",
        value: "@shadow-2, @shadow-inset",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-3",
        value: "var(--td-shadow-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-3-inset",
        value: "@shadow-3, @shadow-inset",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-inset",
        value: "@shadow-inset-top, @shadow-inset-right, @shadow-inset-bottom, @shadow-inset-left",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-inset-bottom",
        value: "var(--td-shadow-inset-bottom)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-inset-left",
        value: "var(--td-shadow-inset-left)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-inset-right",
        value: "var(--td-shadow-inset-right)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@shadow-inset-top",
        value: "var(--td-shadow-inset-top)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-1",
        value: "var(--td-size-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-10",
        value: "var(--td-size-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-11",
        value: "var(--td-size-11)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-12",
        value: "var(--td-size-12)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-13",
        value: "var(--td-size-13)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-14",
        value: "var(--td-size-14)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-15",
        value: "var(--td-size-15)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-16",
        value: "var(--td-size-16)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-2",
        value: "var(--td-size-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-3",
        value: "var(--td-size-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-4",
        value: "var(--td-size-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-5",
        value: "var(--td-size-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-6",
        value: "var(--td-size-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-7",
        value: "var(--td-size-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-8",
        value: "var(--td-size-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@size-9",
        value: "var(--td-size-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer",
        value: "8px",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-1",
        value: "@spacer",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-10",
        value: "@spacer * 10",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-2",
        value: "@spacer * 2",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-3",
        value: "@spacer * 3",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-4",
        value: "@spacer * 4",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-5",
        value: "@spacer * 5",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-6",
        value: "@spacer * 6",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-7",
        value: "@spacer * 7",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-8",
        value: "@spacer * 8",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-9",
        value: "@spacer * 9",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-l",
        value: "@spacer * 1.5",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-m",
        value: "@spacer * 0.75",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@spacer-s",
        value: "@spacer * 0.5",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color",
        value: "var(--td-success-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-1",
        value: "var(--td-success-color-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-10",
        value: "var(--td-success-color-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-2",
        value: "var(--td-success-color-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-3",
        value: "var(--td-success-color-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-4",
        value: "var(--td-success-color-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-5",
        value: "var(--td-success-color-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-6",
        value: "var(--td-success-color-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-7",
        value: "var(--td-success-color-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-8",
        value: "var(--td-success-color-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-9",
        value: "var(--td-success-color-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-active",
        value: "var(--td-success-color-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-disabled",
        value: "var(--td-success-color-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-focus",
        value: "var(--td-success-color-focus)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-hover",
        value: "var(--td-success-color-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-light",
        value: "var(--td-success-color-light)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@success-color-light-hover",
        value: "var(--td-success-color-light-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-anti",
        value: "var(--td-text-color-anti)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-brand",
        value: "var(--td-text-color-brand)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-disabled",
        value: "var(--td-text-color-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-link",
        value: "var(--td-text-color-link)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-placeholder",
        value: "var(--td-text-color-placeholder)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-primary",
        value: "var(--td-text-color-primary)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-color-secondary",
        value: "var(--td-text-color-secondary)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-line-height-base",
        value: "var(--td-line-height-body-medium)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-line-height-l",
        value: "var(--td-line-height-body-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-line-height-s",
        value: "var(--td-line-height-body-small)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-line-height-xl",
        value: "var(--td-line-height-title-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@text-line-height-xxl",
        value: "var(--td-line-height-headline-large)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color",
        value: "var(--td-warning-color)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-1",
        value: "var(--td-warning-color-1)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-10",
        value: "var(--td-warning-color-10)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-2",
        value: "var(--td-warning-color-2)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-3",
        value: "var(--td-warning-color-3)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-4",
        value: "var(--td-warning-color-4)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-5",
        value: "var(--td-warning-color-5)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-6",
        value: "var(--td-warning-color-6)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-7",
        value: "var(--td-warning-color-7)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-8",
        value: "var(--td-warning-color-8)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-9",
        value: "var(--td-warning-color-9)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-active",
        value: "var(--td-warning-color-active)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-disabled",
        value: "var(--td-warning-color-disabled)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-focus",
        value: "var(--td-warning-color-focus)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-hover",
        value: "var(--td-warning-color-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-light",
        value: "var(--td-warning-color-light)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@warning-color-light-hover",
        value: "var(--td-warning-color-light-hover)",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-Notification",
        value: "6000",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-Popup",
        value: "5500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-Tooltip",
        value: "5600",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-affix",
        value: "500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-back-top",
        value: "300",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-dialog",
        value: "2500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-dragging",
        value: "6500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-drawer",
        value: "1500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-guide",
        value: "999999",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-image-viewer",
        value: "3000",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-loading",
        value: "3500",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "@z-index-message",
        value: "6000",
        mode: "alias",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-l",
        value: "var(--td-size-6)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-m",
        value: "var(--td-size-5)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-s",
        value: "var(--td-size-4)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xl",
        value: "var(--td-size-7)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xs",
        value: "var(--td-size-2)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xxl",
        value: "var(--td-size-8)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xxs",
        value: "var(--td-size-1)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xxxl",
        value: "var(--td-size-10)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-margin-xxxxl",
        value: "var(--td-size-12)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-l",
        value: "var(--td-size-6)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-m",
        value: "var(--td-size-5)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-s",
        value: "var(--td-size-4)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-xl",
        value: "var(--td-size-8)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-xs",
        value: "var(--td-size-2)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-xxl",
        value: "var(--td-size-10)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingLR-xxs",
        value: "var(--td-size-1)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-l",
        value: "var(--td-size-6)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-m",
        value: "var(--td-size-5)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-s",
        value: "var(--td-size-4)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-xl",
        value: "var(--td-size-8)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-xs",
        value: "var(--td-size-2)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-xxl",
        value: "var(--td-size-10)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-paddingTB-xxs",
        value: "var(--td-size-1)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-l",
        value: "var(--td-size-11)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-m",
        value: "var(--td-size-10)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-s",
        value: "var(--td-size-9)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xl",
        value: "var(--td-size-12)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xs",
        value: "var(--td-size-8)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxl",
        value: "var(--td-size-13)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxs",
        value: "var(--td-size-7)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxxl",
        value: "var(--td-size-14)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxxs",
        value: "var(--td-size-6)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxxxl",
        value: "var(--td-size-15)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-comp-size-xxxxxl",
        value: "var(--td-size-16)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-body-large",
        value: "var(--td-font-size-body-large) / var(--td-line-height-body-large) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-body-medium",
        value: "var(--td-font-size-body-medium) / var(--td-line-height-body-medium) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-body-small",
        value: "var(--td-font-size-body-small) / var(--td-line-height-body-small) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-display-large",
        value: "600 var(--td-font-size-display-large) / var(--td-line-height-display-large)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-display-medium",
        value: "600 var(--td-font-size-display-medium) / var(--td-line-height-display-medium)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-family",
        value: "PingFang SC, Microsoft YaHei, Arial Regular",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-family-medium",
        value: "PingFang SC, Microsoft YaHei, Arial Medium",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-headline-large",
        value: "600 var(--td-font-size-headline-large) / var(--td-line-height-headline-large)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-headline-medium",
        value: "600 var(--td-font-size-headline-medium) / var(--td-line-height-headline-medium)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-headline-small",
        value: "600 var(--td-font-size-headline-small) / var(--td-line-height-headline-small)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-link-large",
        value: "var(--td-font-size-link-large) / var(--td-line-height-link-large) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-link-medium",
        value: "var(--td-font-size-link-medium) / var(--td-line-height-link-medium) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-link-small",
        value: "var(--td-font-size-link-small) / var(--td-line-height-link-small) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-mark-medium",
        value: "600 var(--td-font-size-mark-medium) / var(--td-line-height-mark-medium) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-mark-small",
        value: "600 var(--td-font-size-mark-small) / var(--td-line-height-mark-small) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-body-large",
        value: "16px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-body-medium",
        value: "14px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-body-small",
        value: "12px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-display-large",
        value: "64px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-display-medium",
        value: "48px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-headline-large",
        value: "36px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-headline-medium",
        value: "28px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-headline-small",
        value: "24px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-link-large",
        value: "16px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-link-medium",
        value: "14px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-link-small",
        value: "12px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-mark-medium",
        value: "14px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-mark-small",
        value: "12px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-title-extraLarge",
        value: "20px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-title-large",
        value: "18px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-title-medium",
        value: "16px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-size-title-small",
        value: "14px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-title-extraLarge",
        value: "600 var(--td-font-size-title-extraLarge) / var(--td-line-height-title-extraLarge)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-title-large",
        value: "600 var(--td-font-size-title-large) / var(--td-line-height-title-large) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-title-medium",
        value: "600 var(--td-font-size-title-medium) / var(--td-line-height-title-medium)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-font-title-small",
        value: "600 var(--td-font-size-title-small) / var(--td-line-height-title-small) var(--td-font-family)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-body-large",
        value: "24px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-body-medium",
        value: "22px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-body-small",
        value: "20px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-display-large",
        value: "72px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-display-medium",
        value: "56px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-headline-large",
        value: "44px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-headline-medium",
        value: "36px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-headline-small",
        value: "32px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-link-large",
        value: "24px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-link-medium",
        value: "22px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-link-small",
        value: "20px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-mark-medium",
        value: "22px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-mark-small",
        value: "20px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-title-extraLarge",
        value: "28px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-title-large",
        value: "26px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-title-medium",
        value: "24px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-line-height-title-small",
        value: "22px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-pop-padding-l",
        value: "var(--td-size-4)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-pop-padding-m",
        value: "var(--td-size-3)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-pop-padding-s",
        value: "var(--td-size-2)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-pop-padding-xl",
        value: "var(--td-size-5)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-pop-padding-xxl",
        value: "var(--td-size-6)",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-circle",
        value: "50%",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-default",
        value: "3px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-extraLarge",
        value: "12px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-large",
        value: "9px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-medium",
        value: "6px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-round",
        value: "999px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-radius-small",
        value: "2px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-1",
        value: "2px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-10",
        value: "32px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-11",
        value: "36px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-12",
        value: "40px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-13",
        value: "48px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-14",
        value: "56px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-15",
        value: "64px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-16",
        value: "72px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-2",
        value: "4px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-3",
        value: "6px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-4",
        value: "8px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-5",
        value: "12px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-6",
        value: "16px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-7",
        value: "20px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-8",
        value: "24px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-size-9",
        value: "28px",
        mode: "common",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component",
        value: "var(--td-gray-color-11)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-active",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-disabled",
        value: "var(--td-gray-color-12)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-hover",
        value: "var(--td-gray-color-10)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container",
        value: "var(--td-gray-color-13)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-active",
        value: "var(--td-gray-color-10)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-hover",
        value: "var(--td-gray-color-12)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-select",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-page",
        value: "var(--td-gray-color-14)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent",
        value: "var(--td-gray-color-10)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent-active",
        value: "var(--td-gray-color-8)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent-hover",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer",
        value: "var(--td-gray-color-12)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer-active",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer-hover",
        value: "var(--td-gray-color-11)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-specialcomponent",
        value: "transparent",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-border-level-1-color",
        value: "var(--td-gray-color-11)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-border-level-2-color",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color",
        value: "var(--td-brand-color-8)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-1",
        value: "#1b2f51",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-10",
        value: "#96bbf8",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-2",
        value: "#173463",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-3",
        value: "#143975",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-4",
        value: "#103d88",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-5",
        value: "#0d429a",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-6",
        value: "#054bbe",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-7",
        value: "#2667d4",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-8",
        value: "#4582e6",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-9",
        value: "#699ef5",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-active",
        value: "var(--td-brand-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-disabled",
        value: "var(--td-brand-color-3)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-focus",
        value: "var(--td-brand-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-hover",
        value: "var(--td-brand-color-7)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-light",
        value: "var(--td-brand-color-1)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-light-hover",
        value: "var(--td-brand-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-component-border",
        value: "var(--td-gray-color-9)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-component-stroke",
        value: "var(--td-gray-color-11)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color",
        value: "var(--td-error-color-6)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-1",
        value: "#472324",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-10",
        value: "#eeced0",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-2",
        value: "#5e2a2d",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-3",
        value: "#703439",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-4",
        value: "#83383e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-5",
        value: "#a03f46",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-6",
        value: "#c64751",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-7",
        value: "#de6670",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-8",
        value: "#ec888e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-9",
        value: "#edb1b6",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-active",
        value: "var(--td-error-color-7)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-disabled",
        value: "var(--td-error-color-3)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-focus",
        value: "var(--td-error-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-hover",
        value: "var(--td-error-color-5)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-light",
        value: "var(--td-error-color-1)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-error-color-light-hover",
        value: "var(--td-error-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-1",
        value: "rgba(0, 0, 0, 90%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-2",
        value: "rgba(0, 0, 0, 60%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-3",
        value: "rgba(0, 0, 0, 40%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-4",
        value: "rgba(0, 0, 0, 26%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-white-1",
        value: "rgba(255, 255, 255, 90%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-white-2",
        value: "rgba(255, 255, 255, 55%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-white-3",
        value: "rgba(255, 255, 255, 35%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-font-white-4",
        value: "rgba(255, 255, 255, 22%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-1",
        value: "#f3f3f3",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-10",
        value: "#4b4b4b",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-11",
        value: "#393939",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-12",
        value: "#2c2c2c",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-13",
        value: "#242424",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-14",
        value: "#181818",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-2",
        value: "#eee",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-3",
        value: "#e8e8e8",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-4",
        value: "#ddd",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-5",
        value: "#c6c6c6",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-6",
        value: "#a6a6a6",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-7",
        value: "#8b8b8b",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-8",
        value: "#777",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-9",
        value: "#5e5e5e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-mask-active",
        value: "rgba(0, 0, 0, 40%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-mask-background",
        value: "rgba(36, 36, 36, 96%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-mask-disabled",
        value: "rgba(0, 0, 0, 60%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-mask-gradient",
        value: "rgba(36, 36, 36, 0%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-scroll-track-color",
        value: "#333",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-scrollbar-color",
        value: "rgba(255, 255, 255, 10%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-scrollbar-hover-color",
        value: "rgba(255, 255, 255, 30%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-1",
        value: "0 4px 6px rgba(0, 0, 0, 6%), 0 1px 10px rgba(0, 0, 0, 8%), 0 2px 4px rgba(0, 0, 0, 12%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-2",
        value: "0 8px 10px rgba(0, 0, 0, 12%), 0 3px 14px rgba(0, 0, 0, 10%), 0 5px 5px rgba(0, 0, 0, 16%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-3",
        value: "0 16px 24px rgba(0, 0, 0, 14%), 0 6px 30px rgba(0, 0, 0, 12%), 0 8px 10px rgba(0, 0, 0, 20%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-bottom",
        value: "inset 0 -.5px 0 #5e5e5e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-left",
        value: "inset -.5px 0 0 #5e5e5e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-right",
        value: "inset .5px 0 0 #5e5e5e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-top",
        value: "inset 0 .5px 0 #5e5e5e",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color",
        value: "var(--td-success-color-5)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-1",
        value: "#193a2a",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-10",
        value: "#deede8",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-2",
        value: "#1a4230",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-3",
        value: "#17533d",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-4",
        value: "#0d7a55",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-5",
        value: "#059465",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-6",
        value: "#43af8a",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-7",
        value: "#46bf96",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-8",
        value: "#80d2b6",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-9",
        value: "#b4e1d3",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-active",
        value: "var(--td-success-color-6)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-disabled",
        value: "var(--td-success-color-3)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-focus",
        value: "var(--td-success-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-hover",
        value: "var(--td-success-color-4)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-light",
        value: "var(--td-success-color-1)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-success-color-light-hover",
        value: "var(--td-success-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-table-shadow-color",
        value: "rgba(0, 0, 0, 55%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-anti",
        value: "#fff",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-brand",
        value: "var(--td-brand-color-8)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-disabled",
        value: "var(--td-font-white-4)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-link",
        value: "var(--td-brand-color-8)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-placeholder",
        value: "var(--td-font-white-3)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-primary",
        value: "var(--td-font-white-1)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-secondary",
        value: "var(--td-font-white-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-text-color-watermark",
        value: "rgba(255, 255, 255, 10%)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color",
        value: "var(--td-warning-color-5)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-1",
        value: "#4f2a1d",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-10",
        value: "#f3e9dc",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-2",
        value: "#582f21",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-3",
        value: "#733c23",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-4",
        value: "#a75d2b",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-5",
        value: "#cf6e2d",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-6",
        value: "#dc7633",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-7",
        value: "#e8935c",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-8",
        value: "#ecbf91",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-9",
        value: "#eed7bf",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-active",
        value: "var(--td-warning-color-6)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-disabled",
        value: "var(--td-warning-color-3)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-focus",
        value: "var(--td-warning-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-hover",
        value: "var(--td-warning-color-4)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-light",
        value: "var(--td-warning-color-1)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-light-hover",
        value: "var(--td-warning-color-2)",
        mode: "dark",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component",
        value: "var(--td-gray-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-active",
        value: "var(--td-gray-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-disabled",
        value: "var(--td-gray-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-component-hover",
        value: "var(--td-gray-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container",
        value: "#fff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-active",
        value: "var(--td-gray-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-hover",
        value: "var(--td-gray-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-container-select",
        value: "#fff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-page",
        value: "var(--td-gray-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent",
        value: "var(--td-gray-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent-active",
        value: "var(--td-gray-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycomponent-hover",
        value: "var(--td-gray-color-5)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer",
        value: "var(--td-gray-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer-active",
        value: "var(--td-gray-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-secondarycontainer-hover",
        value: "var(--td-gray-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-bg-color-specialcomponent",
        value: "#fff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-border-level-1-color",
        value: "var(--td-gray-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-border-level-2-color",
        value: "var(--td-gray-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color",
        value: "var(--td-brand-color-7)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-1",
        value: "#f2f3ff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-10",
        value: "#001a57",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-2",
        value: "#d9e1ff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-3",
        value: "#b5c7ff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-4",
        value: "#8eabff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-5",
        value: "#618dff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-6",
        value: "#366ef4",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-7",
        value: "#0052d9",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-8",
        value: "#003cab",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-9",
        value: "#002a7c",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-active",
        value: "var(--td-brand-color-8)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-disabled",
        value: "var(--td-brand-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-focus",
        value: "var(--td-brand-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-hover",
        value: "var(--td-brand-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-light",
        value: "var(--td-brand-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-brand-color-light-hover",
        value: "var(--td-brand-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-component-border",
        value: "var(--td-gray-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-component-stroke",
        value: "var(--td-gray-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color",
        value: "var(--td-error-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-1",
        value: "#fff0ed",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-10",
        value: "#490002",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-2",
        value: "#ffd8d2",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-3",
        value: "#ffb9b0",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-4",
        value: "#ff9285",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-5",
        value: "#f6685d",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-6",
        value: "#d54941",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-7",
        value: "#ad352f",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-8",
        value: "#881f1c",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-9",
        value: "#68070a",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-active",
        value: "var(--td-error-color-7)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-disabled",
        value: "var(--td-error-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-focus",
        value: "var(--td-error-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-hover",
        value: "var(--td-error-color-5)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-light",
        value: "var(--td-error-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-error-color-light-hover",
        value: "var(--td-error-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-1",
        value: "rgba(0, 0, 0, 90%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-2",
        value: "rgba(0, 0, 0, 60%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-3",
        value: "rgba(0, 0, 0, 40%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-gray-4",
        value: "rgba(0, 0, 0, 26%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-white-1",
        value: "rgba(255, 255, 255, 100%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-white-2",
        value: "rgba(255, 255, 255, 55%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-white-3",
        value: "rgba(255, 255, 255, 35%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-font-white-4",
        value: "rgba(255, 255, 255, 22%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-1",
        value: "#f3f3f3",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-10",
        value: "#4b4b4b",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-11",
        value: "#393939",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-12",
        value: "#2c2c2c",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-13",
        value: "#242424",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-14",
        value: "#181818",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-2",
        value: "#eee",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-3",
        value: "#e8e8e8",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-4",
        value: "#ddd",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-5",
        value: "#c6c6c6",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-6",
        value: "#a6a6a6",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-7",
        value: "#8b8b8b",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-8",
        value: "#777",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-gray-color-9",
        value: "#5e5e5e",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-mask-active",
        value: "rgba(0, 0, 0, 60%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-mask-background",
        value: "rgba(255, 255, 255, 96%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-mask-disabled",
        value: "rgba(255, 255, 255, 60%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-mask-gradient",
        value: "rgba(255, 255, 255, 0%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-scroll-track-color",
        value: "#fff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-scrollbar-color",
        value: "rgba(0, 0, 0, 10%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-scrollbar-hover-color",
        value: "rgba(0, 0, 0, 30%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-1",
        value: "0 1px 10px rgba(0, 0, 0, 5%), 0 4px 5px rgba(0, 0, 0, 8%), 0 2px 4px -1px rgba(0, 0, 0, 12%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-2",
        value: "0 3px 14px 2px rgba(0, 0, 0, 5%), 0 8px 10px 1px rgba(0, 0, 0, 6%), 0 5px 5px -3px rgba(0, 0, 0, 10%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-3",
        value: "0 6px 30px 5px rgba(0, 0, 0, 5%), 0 16px 24px 2px rgba(0, 0, 0, 4%), 0 8px 10px -5px rgba(0, 0, 0, 8%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-bottom",
        value: "inset 0 -.5px 0 #dcdcdc",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-left",
        value: "inset -.5px 0 0 #dcdcdc",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-right",
        value: "inset .5px 0 0 #dcdcdc",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-shadow-inset-top",
        value: "inset 0 .5px 0 #dcdcdc",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color",
        value: "var(--td-success-color-5)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-1",
        value: "#e3f9e9",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-10",
        value: "#002515",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-2",
        value: "#c6f3d7",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-3",
        value: "#92dab2",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-4",
        value: "#56c08d",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-5",
        value: "#2ba471",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-6",
        value: "#008858",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-7",
        value: "#006c45",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-8",
        value: "#005334",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-9",
        value: "#003b23",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-active",
        value: "var(--td-success-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-disabled",
        value: "var(--td-success-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-focus",
        value: "var(--td-success-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-hover",
        value: "var(--td-success-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-light",
        value: "var(--td-success-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-success-color-light-hover",
        value: "var(--td-success-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-table-shadow-color",
        value: "rgba(0, 0, 0, 8%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-anti",
        value: "#fff",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-brand",
        value: "var(--td-brand-color-7)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-disabled",
        value: "var(--td-font-gray-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-link",
        value: "var(--td-brand-color-8)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-placeholder",
        value: "var(--td-font-gray-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-primary",
        value: "var(--td-font-gray-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-secondary",
        value: "var(--td-font-gray-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-text-color-watermark",
        value: "rgba(0, 0, 0, 10%)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color",
        value: "var(--td-warning-color-5)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-1",
        value: "#fff1e9",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-10",
        value: "#3b1700",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-2",
        value: "#ffd9c2",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-3",
        value: "#ffb98c",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-4",
        value: "#fa9550",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-5",
        value: "#e37318",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-6",
        value: "#be5a00",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-7",
        value: "#954500",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-8",
        value: "#713300",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-9",
        value: "#532300",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-active",
        value: "var(--td-warning-color-6)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-disabled",
        value: "var(--td-warning-color-3)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-focus",
        value: "var(--td-warning-color-2)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-hover",
        value: "var(--td-warning-color-4)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-light",
        value: "var(--td-warning-color-1)",
        mode: "light",
    },
    UpstreamThemeToken {
        name: "--td-warning-color-light-hover",
        value: "var(--td-warning-color-2)",
        mode: "light",
    },
];
